export const listData = [
  {
    id: 1,
    name: "Michael",
    company: 1,
    phone: "(225) 555-0118",
    email: "jane@microsoft.com",
    country: "United States",
    status: "Active",
  },
  {
    id: 2,
    name: "Michael",
    company: 1,
    phone: "(225) 555-0118",
    email: "jane@microsoft.com",
    country: "United States",
    status: "Active",
  },
  {
    id: 3,
    name: "Michael",
    company: 1,
    phone: "(225) 555-0118",
    email: "jane@microsoft.com",
    country: "United States",
    status: "Active",
  },
  {
    id: 4,
    name: "Michael",
    company: 1,
    phone: "(225) 555-0118",
    email: "jane@microsoft.com",
    country: "United States",
    status: "Active",
  },
  {
    id: 5,
    name: "Michael",
    company: 1,
    phone: "(225) 555-0118",
    email: "jane@microsoft.com",
    country: "United States",
    status: "Active",
  },
];
